triggers:
  - name: trigger-deploy-test
    type: trigger
    version:
      message: 'testing trigger in test'
    flags:
      - hello
  - name: trigger-deploy-prod
    type: trigger
    version:
      message: 'testing trigger in test'
    flags:
      - hello
